import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { login } from "./ui-helpers";
const fixture = "http://127.0.0.1:45432";
test("first visit, real meal actions, lock persistence, replay and keyboard access", async ({ page, request }, info) => {
  await request.post(`${fixture}/fixture/reset`, { data: { preferences: { tutorial_seen_version: 0 } } });
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await login(page);
  const catalog = page.getByRole("dialog", { name: "跟着做一遍" });
  await expect(catalog).toBeVisible();
  await page.screenshot({ path: info.outputPath("tutorial-welcome.png") });
  await catalog.getByRole("button", { name: /安排第一餐/ }).click();
  const guide = page.getByRole("region", { name: "操作引导" });
  await expect(guide.getByRole("button", { name: "继续", exact: true })).toBeDisabled();
  await page.locator('[data-tour="meal-add"]').click();
  const picker = page.getByRole("dialog", { name: "添加食物", exact: true });
  await picker.getByRole("textbox", { name: "搜索食物", exact: true }).fill("燕麦片");
  await expect(picker.getByText("燕麦片", { exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("tutorial-picker.png") });
  expect((await new AxeBuilder({ page }).analyze()).violations.filter(v => ["serious","critical"].includes(v.impact ?? ""))).toEqual([]);
  await picker.getByText("燕麦片", { exact: true }).click();
  await expect(guide.getByRole("button", { name: "继续", exact: true })).toBeEnabled();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.getByLabel("燕麦片克重", { exact: true }).fill("80");
  await guide.getByRole("heading").click();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  const lock = page.getByRole("button", { name: "锁定燕麦片分量", exact: true });
  await expect(lock).toHaveAttribute("aria-pressed", "true");
  await lock.click();
  await expect(lock).toHaveAttribute("aria-pressed", "false");
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.getByRole("button", { name: "锁定整餐", exact: true }).click();
  await expect(lock).toBeDisabled();
  await page.screenshot({ path: info.outputPath("tutorial-locks.png") });
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.getByRole("button", { name: "保存计划", exact: true }).click();
  await expect(guide.getByRole("button", { name: "完成这一段", exact: true })).toBeEnabled();
  await guide.getByRole("button", { name: "完成这一段", exact: true }).click();
  await page.getByRole("button", { name: "开始自己使用", exact: true }).click();
  await expect.poll(async () => (await (await request.get(`${fixture}/fixture/state`)).json()).profiles[0].tutorial_seen_version).toBe(1);
  await page.reload();
  await expect(page.getByRole("button", { name: "锁定整餐", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByLabel("燕麦片克重", { exact: true })).toHaveValue("80");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "查看教程", exact: true }).filter({ visible: true }).click();
  await expect(catalog).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(catalog).toHaveCount(0);
  expect(await page.locator("body").evaluate(el => el.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
});
test("test users see the tutorial on re-entry but not every route change", async ({ page, request }) => {
  await request.post(`${fixture}/fixture/reset`, { data: { preferences: { tutorial_seen_version: 1, tutorial_every_visit: true } } });
  await login(page);
  await expect(page.getByRole("dialog", { name: "跟着做一遍" })).toBeVisible();
  await page.getByRole("button", { name: "暂时跳过", exact: true }).click();
  await page.getByRole("link", { name: "食物库", exact: true }).filter({ visible: true }).click();
  await expect(page.getByRole("heading", { name: "我的食物与公共食物" })).toBeVisible();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole("dialog", { name: "跟着做一遍" })).toBeVisible();
});

test("other chapters guide real goals and intake, then food search and history in dark mode", async ({ page, request }, info) => {
  await request.post(`${fixture}/fixture/reset`, { data: { preferences: { theme: "dark" } } });
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await login(page);
  await page.getByRole("button", { name: "查看教程", exact: true }).filter({ visible: true }).click();
  await page.getByRole("button", { name: /设置饮食目标/ }).click();
  const guide = page.getByRole("region", { name: "操作引导" });
  await page.getByLabel("每日碳水 g", { exact: true }).fill("230");
  await page.getByLabel("每日蛋白质 g", { exact: true }).fill("175");
  await page.getByLabel("每日脂肪 g", { exact: true }).fill("65");
  await page.getByLabel(/我已成年/).check();
  await page.getByRole("button", { name: "预览调整", exact: true }).click();
  await page.getByRole("button", { name: "确认目标", exact: true }).click();
  await expect(guide.getByRole("button", { name: "完成这一段", exact: true })).toBeEnabled();
  await guide.getByRole("button", { name: "完成这一段", exact: true }).click();
  await page.getByRole("button", { name: /记录每天的变化/ }).click();
  await page.getByRole("button", { name: "记录食物或饮料", exact: true }).click();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.getByRole("button", { name: "添加实际食物", exact: true }).click();
  const picker = page.getByRole("dialog", { name: "选择实际食物", exact: true });
  await picker.getByLabel("搜索食物", { exact: true }).fill("燕麦片");
  await picker.getByText("燕麦片", { exact: true }).click();
  await page.getByRole("button", { name: "保存饮食记录", exact: true }).click();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await expect(page.getByRole("link", { name: "训练", exact: true })).toHaveAttribute("aria-current", "page");
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await expect(page.getByRole("link", { name: "身体数据", exact: true })).toHaveAttribute("aria-current", "page");
  await guide.getByRole("button", { name: "完成这一段", exact: true }).click();
  await page.getByRole("button", { name: /管理自己的食物/ }).click();
  await page.getByLabel("搜索食物", { exact: true }).fill("燕麦");
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.locator('[data-tour="food-create"]').click();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await page.screenshot({ path: info.outputPath("tutorial-food-form-dark.png") });
  expect((await new AxeBuilder({ page }).analyze()).violations.filter(v => ["serious","critical"].includes(v.impact ?? ""))).toEqual([]);
  await page.getByRole("button", { name: "关闭添加食物", exact: true }).click();
  await guide.getByRole("button", { name: "完成这一段", exact: true }).click();
  await page.getByRole("button", { name: /查看趋势与历史/ }).click();
  await page.getByRole("link", { name: "饮食计划", exact: true }).click();
  await guide.getByRole("button", { name: "继续", exact: true }).click();
  await expect(page).toHaveURL(/\/calendar/);
  await guide.getByRole("button", { name: "完成这一段", exact: true }).click();
  await page.getByRole("button", { name: "开始自己使用", exact: true }).click();
  const state = await (await request.get(`${fixture}/fixture/state`)).json();
  expect(state.daily_checkins[0].actual.mealEvents[0].actualFoodEntries[0].grams).toBe(100);
  expect(state.user_plan_protocols).toHaveLength(1);
  expect(state.foods).toHaveLength(0);
  expect(errors).toEqual([]);
});

test("a failed real save cannot complete a step; skipping is reported as ending", async ({ page, request }) => {
  await request.post(`${fixture}/fixture/reset`);
  await login(page);
  await page.getByRole("button", { name: "查看教程", exact: true }).filter({ visible: true }).click();
  await page.getByRole("button", { name: /安排第一餐/ }).click();
  const guide = page.getByRole("region", { name: "操作引导" });
  for (let i = 0; i < 4; i++) await guide.getByRole("button", { name: "跳过这一步", exact: true }).click();
  await page.route("**/rest/v1/daily_plans**", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ message: "synthetic save failure" }) }));
  await page.getByRole("button", { name: "保存计划", exact: true }).click();
  await expect(page.getByText("保存失败。", { exact: true })).toBeVisible();
  await expect(guide.getByRole("button", { name: "完成这一段", exact: true })).toBeDisabled();
  await guide.getByRole("button", { name: "跳过这一步", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "这一段已结束" })).toBeVisible();
  const state = await (await request.get(`${fixture}/fixture/state`)).json();
  expect(state.daily_plans).toHaveLength(0);
});
