import { describe,expect,it } from "vitest";
import { createTreProtocol } from "@/lib/planPresets";
import { addDays } from "@/lib/dateTime";
import { emptyActualV3 } from "@/lib/actualIntake";
import { reviewProgress } from "@/lib/progressReview";
import type { BodyLog } from "@/lib/bodyLogs";
import type { DailyCheckin } from "@/lib/types";
const protocol=createTreProtocol({id:"40000000-0000-4000-8000-000000000001",effectiveFrom:"2026-01-01",cycleAnchorDate:"2026-01-01",timeZone:"Asia/Shanghai"});
function synthetic(days:number,weeklyLoss=0.1){const logs:BodyLog[]=[];const checkins:DailyCheckin[]=[];for(let i=0;i<days;i++){const date=addDays(protocol.effectiveFrom,i);logs.push({logDate:date,weightKg:80-i*weeklyLoss/7,waistCm:90});checkins.push({id:`test-${i}`,planDate:date,target:protocol.dailyTarget,completed:true,createdAt:"",updatedAt:"",actual:{...emptyActualV3({version:2,foods:[],exercises:[],bmrKcal:0,activityKcal:0,totalsSnapshot:protocol.dailyTarget}),intakeComplete:true,habits:{sleepHours:8},recovery:{fatigue:1,footPain:0,trainingTolerance:"good",persistentSymptoms:false}}});}return {logs,checkins,end:addDays(protocol.effectiveFrom,days-1)};}
describe("quality-gated progress review",()=>{
  it("D05 needs 21 days for two week-on-week comparisons",()=>{const d=synthetic(14);const r=reviewProgress(protocol,d.end,d.logs,d.checkins);expect(r.status).toBe("insufficient_data");expect(r.weeklyLoss).toHaveLength(1);expect(r.adjustmentKcal).toBeNull();});
  it("D04 reports actual sample counts without treating missing days as zero",()=>{const d=synthetic(21);const r=reviewProgress(protocol,d.end,d.logs.slice(0,15),d.checkins.slice(0,15));expect(r.status).toBe("insufficient_data");expect(r.windows[2]).toMatchObject({weightSamples:1,intakeDays:1});expect(r.windows[2].meanIntake).toBe(2205);});
  it("D06 observes falling waist despite a flat weight trend",()=>{const d=synthetic(21);d.logs.forEach((l,i)=>{l.waistCm=90-i*0.1;});expect(reviewProgress(protocol,d.end,d.logs,d.checkins).status).toBe("maintain");});
  it("waist loss does not mask a sustained rapid weight-loss review",()=>{const d=synthetic(28,1);d.logs.forEach((l,i)=>{l.waistCm=90-i*0.1;});expect(reviewProgress(protocol,d.end,d.logs,d.checkins)).toMatchObject({status:"consider_increase",adjustmentKcal:125});});
  it("D07 does not infer a stable waist/recovery and blocks restriction for persistent symptoms",()=>{const d=synthetic(21);d.logs.forEach(l=>{l.waistCm=null;});expect(reviewProgress(protocol,d.end,d.logs,d.checkins).status).toBe("review_intake");d.checkins.forEach(c=>{if(c.actual.version===3)delete c.actual.recovery;});expect(reviewProgress(protocol,d.end,d.logs,d.checkins).recovery).toBe("unknown");const a=d.checkins.at(-1)!.actual;if(a.version===3)a.recovery={persistentSymptoms:true};const r=reviewProgress(protocol,d.end,d.logs,d.checkins);expect(r.status).toBe("recovery_first");expect(r.adjustmentKcal).toBeNull();});
  it("only offers a small reduction after reliable stable observations, and resets after target change",()=>{const d=synthetic(21);expect(reviewProgress(protocol,d.end,d.logs,d.checkins)).toMatchObject({status:"consider_small_decrease",adjustmentKcal:-125});expect(reviewProgress({...protocol,effectiveFrom:addDays(d.end,-1)},d.end,d.logs,d.checkins).status).toBe("insufficient_data");d.checkins[15].completed=false;d.checkins[16].completed=false;expect(reviewProgress(protocol,d.end,d.logs,d.checkins).status).toBe("review_intake");});
  it("excludes the first week from rapid-loss escalation and uses later valid windows",()=>{const early=synthetic(21,1);expect(reviewProgress(protocol,early.end,early.logs,early.checkins).adjustmentKcal).toBeNull();const later=synthetic(28,1);expect(reviewProgress(protocol,later.end,later.logs,later.checkins)).toMatchObject({status:"consider_increase",adjustmentKcal:125});const moderate=synthetic(21,0.5);expect(reviewProgress(protocol,moderate.end,moderate.logs,moderate.checkins).status).toBe("maintain");});
});
