import type { FoodItem } from "@/lib/types";

export const builtinFoods: FoodItem[] = [
  {
    id: "public-rice-cooked",
    name: "白米饭",
    category: "主食",
    kcalPer100g: 130,
    fatPer100g: 0.21,
    carbsPer100g: 28.59,
    proteinPer100g: 2.38,
    weightBasis: "cooked",
    cookedRawRatio: 2.5,
    source: "public"
  },
  {
    id: "public-oats-raw",
    name: "燕麦片",
    category: "主食",
    kcalPer100g: 379,
    fatPer100g: 6.5,
    carbsPer100g: 67.7,
    proteinPer100g: 13.2,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-sweet-potato-cooked",
    name: "红薯",
    category: "主食",
    kcalPer100g: 86,
    fatPer100g: 0.1,
    carbsPer100g: 20.1,
    proteinPer100g: 1.6,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-potato-cooked",
    name: "土豆",
    category: "主食",
    kcalPer100g: 87,
    fatPer100g: 0.1,
    carbsPer100g: 20.1,
    proteinPer100g: 1.9,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-noodle-cooked",
    name: "面条",
    category: "主食",
    kcalPer100g: 138,
    fatPer100g: 2.1,
    carbsPer100g: 25,
    proteinPer100g: 4.5,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-broccoli-cooked",
    name: "西兰花",
    category: "蔬菜",
    kcalPer100g: 35,
    fatPer100g: 0.4,
    carbsPer100g: 7.2,
    proteinPer100g: 2.4,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-spinach-cooked",
    name: "菠菜",
    category: "蔬菜",
    kcalPer100g: 23,
    fatPer100g: 0.3,
    carbsPer100g: 3.8,
    proteinPer100g: 3,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-lettuce-raw",
    name: "生菜",
    category: "蔬菜",
    kcalPer100g: 15,
    fatPer100g: 0.2,
    carbsPer100g: 2.9,
    proteinPer100g: 1.4,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-tomato-raw",
    name: "番茄",
    category: "蔬菜",
    kcalPer100g: 18,
    fatPer100g: 0.2,
    carbsPer100g: 3.9,
    proteinPer100g: 0.9,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-cucumber-raw",
    name: "黄瓜",
    category: "蔬菜",
    kcalPer100g: 15,
    fatPer100g: 0.1,
    carbsPer100g: 3.6,
    proteinPer100g: 0.7,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-banana-raw",
    name: "香蕉",
    category: "水果",
    kcalPer100g: 89,
    fatPer100g: 0.3,
    carbsPer100g: 22.8,
    proteinPer100g: 1.1,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-apple-raw",
    name: "苹果",
    category: "水果",
    kcalPer100g: 52,
    fatPer100g: 0.2,
    carbsPer100g: 13.8,
    proteinPer100g: 0.3,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-orange-raw",
    name: "橙子",
    category: "水果",
    kcalPer100g: 47,
    fatPer100g: 0.1,
    carbsPer100g: 11.8,
    proteinPer100g: 0.9,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-blueberry-raw",
    name: "蓝莓",
    category: "水果",
    kcalPer100g: 57,
    fatPer100g: 0.3,
    carbsPer100g: 14.5,
    proteinPer100g: 0.7,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-kiwi-raw",
    name: "猕猴桃",
    category: "水果",
    kcalPer100g: 61,
    fatPer100g: 0.5,
    carbsPer100g: 14.7,
    proteinPer100g: 1.1,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-chicken-breast-cooked",
    name: "鸡胸肉",
    category: "肉类",
    kcalPer100g: 165,
    fatPer100g: 3.6,
    carbsPer100g: 0,
    proteinPer100g: 31,
    weightBasis: "cooked",
    cookedRawRatio: 0.75,
    source: "public"
  },
  {
    id: "public-lean-beef-cooked",
    name: "瘦牛肉",
    category: "肉类",
    kcalPer100g: 217,
    fatPer100g: 11.8,
    carbsPer100g: 0,
    proteinPer100g: 26.1,
    weightBasis: "cooked",
    cookedRawRatio: 0.75,
    source: "public"
  },
  {
    id: "public-salmon-cooked",
    name: "三文鱼",
    category: "肉类",
    kcalPer100g: 206,
    fatPer100g: 12.4,
    carbsPer100g: 0,
    proteinPer100g: 22.1,
    weightBasis: "cooked",
    cookedRawRatio: 0.8,
    source: "public"
  },
  {
    id: "public-egg-whole",
    name: "鸡蛋",
    category: "肉类",
    kcalPer100g: 143,
    fatPer100g: 9.5,
    carbsPer100g: 0.7,
    proteinPer100g: 12.6,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-shrimp-cooked",
    name: "虾仁",
    category: "肉类",
    kcalPer100g: 99,
    fatPer100g: 0.3,
    carbsPer100g: 0.2,
    proteinPer100g: 24,
    weightBasis: "cooked",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-whey",
    name: "乳清蛋白粉",
    category: "补剂",
    kcalPer100g: 390,
    fatPer100g: 6,
    carbsPer100g: 8,
    proteinPer100g: 76,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-creatine",
    name: "肌酸",
    category: "补剂",
    kcalPer100g: 0,
    fatPer100g: 0,
    carbsPer100g: 0,
    proteinPer100g: 0,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-casein",
    name: "酪蛋白粉",
    category: "补剂",
    kcalPer100g: 370,
    fatPer100g: 2,
    carbsPer100g: 10,
    proteinPer100g: 78,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-electrolyte",
    name: "电解质粉",
    category: "补剂",
    kcalPer100g: 120,
    fatPer100g: 0,
    carbsPer100g: 30,
    proteinPer100g: 0,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-fish-oil",
    name: "鱼油",
    category: "补剂",
    kcalPer100g: 900,
    fatPer100g: 100,
    carbsPer100g: 0,
    proteinPer100g: 0,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-almond",
    name: "杏仁",
    category: "坚果",
    kcalPer100g: 579,
    fatPer100g: 49.9,
    carbsPer100g: 21.6,
    proteinPer100g: 21.2,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-walnut",
    name: "核桃",
    category: "坚果",
    kcalPer100g: 654,
    fatPer100g: 65.2,
    carbsPer100g: 13.7,
    proteinPer100g: 15.2,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-cashew",
    name: "腰果",
    category: "坚果",
    kcalPer100g: 553,
    fatPer100g: 43.9,
    carbsPer100g: 30.2,
    proteinPer100g: 18.2,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-peanut",
    name: "花生",
    category: "坚果",
    kcalPer100g: 567,
    fatPer100g: 49.2,
    carbsPer100g: 16.1,
    proteinPer100g: 25.8,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  },
  {
    id: "public-pistachio",
    name: "开心果",
    category: "坚果",
    kcalPer100g: 560,
    fatPer100g: 45.3,
    carbsPer100g: 27.2,
    proteinPer100g: 20.2,
    weightBasis: "raw",
    cookedRawRatio: null,
    source: "public"
  }
];

