import { describe,expect,it } from "vitest";
import { createTreProtocol } from "@/lib/planPresets";
import { cycleDay, previewCycle, previewScheduleDelay, rptRecoveryTemplate, setsFromPrescription, equivalentWeeklySets, completedSetSummary } from "@/lib/trainingCycle";
import { addDays } from "@/lib/dateTime";
import { applyDeloadToTemplate, bestE1RMByExercise, weeklyWorkingSets } from "@/lib/training";
import { mapWorkoutSessionRow, workoutSessionToRow } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";
import type { WorkoutSession } from "@/lib/types";
const protocol=createTreProtocol({id:"30000000-0000-4000-8000-000000000001",effectiveFrom:"2026-01-29",cycleAnchorDate:"2026-01-29",timeZone:"Asia/Shanghai"});
const session=(date:string):WorkoutSession=>({id:"s1",sessionDate:date,splitLabel:"合成测试",createdAt:"",status:"recorded",sets:setsFromPrescription(rptRecoveryTemplate.days[0],()=>crypto.randomUUID())});
describe("8-day recovery training contracts",()=>{
  it("W01/W02 rotates D1—D16 across months without a calendar week reset",()=>{expect(cycleDay(protocol,"2026-01-28")).toBeNull();const days=Array.from({length:16},(_,i)=>cycleDay(protocol,addDays(protocol.effectiveFrom,i))!);expect(days.map(d=>d.index)).toEqual([0,1,2,3,4,5,6,7,0,1,2,3,4,5,6,7]);expect(days[7].prescription).toBeNull();expect(days[8].prescription!.dayLabel).toContain("D1");expect(days[8].reviewDue).toBe(true);});
  it("W03/W10 preserves occupied dates and validates delay before making any writes",()=>{const rows=previewCycle(protocol,protocol.effectiveFrom,16,[],[]);expect(previewCycle(protocol,protocol.effectiveFrom,16,rows,[])).toEqual([]);expect(previewCycle(protocol,protocol.effectiveFrom,16,[],[session(protocol.effectiveFrom)])).toHaveLength(15);expect(()=>previewScheduleDelay(rows,[session(protocol.effectiveFrom)],protocol.effectiveFrom,2)).toThrow();expect(()=>previewScheduleDelay([{...rows[0],manuallyEdited:true},...rows.slice(1)],[],protocol.effectiveFrom,2)).toThrow();const shifted=previewScheduleDelay(rows,[],protocol.effectiveFrom,2);expect(shifted.slice(0,2).every(s=>s.dayKind==="rest")).toBe(true);expect(shifted[2].prescription).toEqual(rows[0].prescription);});
  it("W04/W07 makes three different prescriptions without fabricated actual repetitions/RIR",()=>{const s=session(protocol.effectiveFrom);expect(s.sets.slice(0,3).map(s=>s.prescription?.repRange)).toEqual([[5,7],[6,9],[7,10]]);expect(s.sets.every(s=>s.rir===null && s.completed===false)).toBe(true);expect(completedSetSummary([s]).total).toBe(0);expect(weeklyWorkingSets([s],protocol.effectiveFrom).chest).toBe(0);});
  it("W05/W06/W08/W11 counts explicitly completed bodyweight sets without inferring RIR or 1RM",()=>{const s=session(protocol.effectiveFrom);s.sets=s.sets.slice(0,3).map((set,i)=>({...set,loadType:"bodyweight",weightKg:0,reps:8,completed:i<2,rir:i===0?null:2,isWarmup:i===1}));expect(completedSetSummary([s])).toEqual({total:1,closeToFailure:0});expect(bestE1RMByExercise(s)).toEqual([]);const old=mapWorkoutSessionRow({id:"legacy",session_date:s.sessionDate,split_label:"旧日志",created_at:"",sets:[{id:"legacy-set",exercise:"引体",muscleGroup:"back",weightKg:0,reps:8,rir:2,isWarmup:false}]});expect(old.status).toBe("legacy_unknown");expect(old.sets).toHaveLength(1);expect(completedSetSummary([old]).total).toBe(0);});
  it("W09/W12 does not halve recovery twice; uses an explicit eight-day denominator",()=>{expect(applyDeloadToTemplate(rptRecoveryTemplate)).toEqual(rptRecoveryTemplate);expect(equivalentWeeklySets(12,8)).toBe(10.5);const chest=rptRecoveryTemplate.days[0].exercises.filter(e=>e.muscleGroup==="chest").reduce((sum,e)=>sum+e.sets,0);expect(chest).toBe(9);expect(equivalentWeeklySets(chest,8)).toBe(7.875);});
  it("round-trips completed timed core with side and equipment and deduplicates IDs in statistics",()=>{const s=session(protocol.effectiveFrom);s.sets=[{...s.sets[0],loadType:"timed",durationSeconds:30,reps:0,weightKg:0,side:"left",completed:true,equipmentId:"mat-1"}];const row=workoutSessionToRow(s,{id:"user"} as User);const restored=mapWorkoutSessionRow({...row,id:s.id,created_at:"",status:"recorded",revision:2,schedule_id:"schedule-1"});expect(restored.sets).toEqual(s.sets);expect(restored.revision).toBe(2);expect(restored.scheduleId).toBe("schedule-1");expect(bestE1RMByExercise(restored)).toEqual([]);expect(completedSetSummary([restored,restored]).total).toBe(1);});
});
